/**
 * Code snippets that appear in more than one place: the landing page, the docs,
 * and the example README. This file is the only source. The README copy is
 * generated by scripts/sync-generated.mjs and checked in CI.
 */
import { REPO, SERVER } from "./measurements";

export const RUN = `git clone ${REPO}
cd tollbooth
npm install
npm run build

export MOOVE_API_KEY=mk_live_...
# Only if your key names a different host. Do not guess it.
# export MOOVE_API_BASE_URL=https://api.moove.xyz

node examples/research-tools/dist/stdio.js`;

export const TOOL = `server.paidTool(
  'fetch_readable',
  'Fetch a web page and return its readable text.',
  { sku: 'research', cost: 1 },   // an expensive tool can cost more
  { url: z.string() },
  { readOnlyHint: true },
  async (args) => readable(String(args.url))
);`;

export const CLIENT = `{
  "mcpServers": {
    "tollbooth-research": {
      "command": "npx",
      "args": ["-y", "mcp-remote", "${SERVER}/mcp"]
    }
  }
}`;

export const WITH_PAYWALL = `import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { definePrice } from '@tollbooth/core';
import { withPaywall } from '@tollbooth/mcp';
import { MooveClient, MooveProvider } from '@tollbooth/moove';
import { SqliteEntitlementStore } from '@tollbooth/store-sqlite';

const store = new SqliteEntitlementStore({ path: './tollbooth.sqlite' });

const provider = new MooveProvider({
  client: new MooveClient({ apiKey: process.env.MOOVE_API_KEY! }),
  store,
  prices: [
    definePrice({
      sku: 'research',
      unit: 'credit_pack',
      amount: '10.00',      // decimal string, never a number
      credits: 250,
      label: 'Research tools — 250 credits',
    }),
  ],
});

const server = withPaywall(
  new McpServer({ name: 'my-server', version: '0.1.0' }),
  { provider, store }
);`;

export const PRICES = `definePrice({ sku: 'once',  unit: 'per_call',    amount: '0.05' });
definePrice({ sku: 'pack',  unit: 'credit_pack', amount: '10.00', credits: 250 });
definePrice({ sku: 'day',   unit: 'time_pass',   amount: '20.00', ttlMs: 86_400_000 });`;

export const POSTGRES = `import { PostgresEntitlementStore } from '@tollbooth/store-postgres';

const store = new PostgresEntitlementStore({
  connectionString: process.env.DATABASE_URL!,   // Neon: use the *pooled* host
});
await store.ready();   // runs migrations under an advisory lock`;

export const SETTLEMENT_POLICY = `new MooveProvider({
  client, store, prices,
  chargeTtlMs: 60 * 60 * 1000,          // default; floor 15 minutes
  settlementPolicy: {
    toleranceFraction: 0.005,           // within 0.5%: grant in full
    minimumFraction: 0.1,               // below 10%: grant nothing
  },
  subjectTtlMs: 30 * 24 * 60 * 60 * 1000, // sliding; floor 1 hour
});`;
